### ISSUE TITLE
Google's new continuous scrolling based on English & US-based search results, breaks compatibility.

### ISSUE THREAD

**Issue by z0xyz** [iorate/ublacklist#302] opened 2022-12-16 17:41 UTC
## Expected Behavior
All listed search results to be either blocked or showing the link to block it

## Actual Behavior
Previously blocked search results i.e. sites, are now visible, and all of the current search results no longer show `Block this site`
## Steps to Reproduce the Problem

1. Head out to google's search setting from the `gear icon`, the `See all Search settings`
1. Region settings, then selected the United States
1. Change the language to English

## Specifications

- Browser: Version 108.0.5359.98 (Official Build) (64-bit)

- Search engine: Google
- Language: English
- Region: United States

**Comment by iorate** [comment] 2022-12-17 00:05
Duplicate of #299 
This issue will be fixed in v8.2.3.

**Closed by iorate** 2022-12-17 00:05 UTC

**Comment by z0xyz** [comment] 2022-12-17 11:31
It's still persistent even after the latest update v8.2.3 obtained via the Google chrome Store.
