### ISSUE TITLE
UBlacklist Firefox v8.3.1 not working for Google Search Images

### ISSUE THREAD

**Issue by bidoofisnotonfire** [iorate/ublacklist#355] opened 2023-08-02 01:27 UTC
UBlacklist for Firefox v8.3.1 doesn't work at all for the Google search images section.
![image](https://github.com/iorate/ublacklist/assets/141194266/046fa165-4d1c-444a-94f9-12e9a281f830)
As you can see, the "Block this site" text is nowhere to be found despite the "Hide the block this site links" not being enabled.
![image](https://github.com/iorate/ublacklist/assets/141194266/8b22a7f2-c513-43cc-b68b-22210c9b3c49)

But in other sections (e.g. news, videos), it works totally fine.
![image](https://github.com/iorate/ublacklist/assets/141194266/a168aa63-53ca-447e-a674-93a3a64c4f28)
![image](https://github.com/iorate/ublacklist/assets/141194266/d999ed8b-d6a1-4f80-aa23-fd9df150a60d)
![image](https://github.com/iorate/ublacklist/assets/141194266/74c34555-e5a4-4c1f-a8da-e67ff0fd09ff)

Is anyone else having this problem?

**Comment by chrishazfun** [comment] 2023-08-02 13:07
Had Pinterest results show up with the list enabled, I think something updated on Firefox's end

**Comment by iorate** [comment] 2023-08-05 09:57
This is a duplicate of #352.
See also:  #354

**Closed by iorate** 2023-08-05 09:57 UTC
