### ISSUE TITLE
Using uBlacklist in Edge for Bing won't work

### ISSUE THREAD

**Issue by itsmetoolala** [iorate/ublacklist#328] opened 2023-03-19 07:42 UTC
- Browser: Edge
- Search engine: bing (only, 'though I only use google & duckduckgo where uBlacklist works great!)

In Chrome it works on bing! Only in Edge it does not.

**Comment by iorate** [comment] 2023-03-28 14:10
probable duplicate of #318 
see also: #319

**Closed by iorate** 2023-03-28 14:10 UTC
