### ISSUE TITLE
"Block this site" overlay "Translate this page"

### ISSUE THREAD

**Issue by PoiScript** [iorate/uBlacklist#36] opened 2020-04-15 10:02 UTC
<img width="863" alt="Screen Shot 2020-04-15 at 5 48 24 PM" src="https://user-images.githubusercontent.com/17513314/79323898-65752800-7f41-11ea-8327-c5b965100b14.png">

## Expected Behavior

Buttons display side by side.

## Actual Behavior

They're overlapped.

## Steps to Reproduce the Problem

  1. Use English as the default language of Google Search.
  2. Search for "最新 バージョン Android"

## Specifications

  - OS: macOS Catalina
  - Browser: Google Chrome 81
  - Other extensions that might interfere: Not sure

**Comment by iorate** [comment] 2020-05-11 13:30
@PoiScript 
Sorry for my late reply & thank you for your bug report.

I finally reproduced this 'overlay' bug on macOS Catalina. 
I never found it on Windows 10, so it may be platform-specific.

It will be fixed in the next version.

**Closed** 2020-05-12 14:25 UTC

**Comment by Fikafusik** [comment] 2020-05-12 14:43
@iorate 
Faced this problem several months ago. Now failed to reproduce this bug. There is a feeling that this periodically happens due to a poor Internet connection.

OS: Windows 10 (x64)
Browser: Mozilla Firefox

**Comment by iorate** [comment] 2020-05-12 15:16
@Fikafusik 
This bug should be fixed in v3.8.0. Please give it a try. (Currently under review)
