### ISSUE TITLE
Extension Broken for Duckduckgo Search

### ISSUE THREAD

**Issue by Ijaxxus** [iorate/ublacklist#226] opened 2022-04-30 15:24 UTC
Extension completely stopped working on Duckduckgo. Still works on other search engines.

**Comment by jedivulcan** [comment] 2022-04-30 21:02
Same. Broke for me yesterday, too. Safari - iOS/Mac & Firefox - Mac.

**Comment by SilenceIsG0lden** [comment] 2022-04-30 23:17
Not working anymore on Bing either (and thus Ecosia). Am swamped again with Amazon-everything. Ugh. No escaping. Help!!!!

**Comment by pqppq** [comment] 2022-05-01 00:19
same / in Chrome browser

**Comment by parapacem** [comment] 2022-05-01 19:02
same here. Yandex browser (chromium) and it works on Google in this browser. all addons/extensions turned off and still happens. noticed it when a CNN result came up in search...

**Comment by acook** [comment] 2022-05-01 20:44
Confirmed here as well. I've tested it with various other plugins disabled and it is still happening.

I'm on Firefox, so it seems that DDG changed something that affects everyone.

**Comment by rahulmangaldas** [comment] 2022-05-03 02:56
Same, not working on DDG on Edge (Windows/macOS) and Safari (iOS)

**Comment by kphrx** [comment] 2022-05-03 10:16
It looks like DuckDuckGo is using React to display search results, which is probably the cause.

**Comment by SilenceIsG0lden** [comment] 2022-05-03 19:47
> It looks like DuckDuckGo is using React to display search results, which is probably the cause.

I know this thread is for DDG specifically, but -- as I stated in my original comment -- this also applies to Bing and every search engine that is built on Bing, like Ecosia. (Not quite sure if DDG also uses Bing.) So maybe Bing is the culprit? The extension still works on Google, which I don't use.

**Comment by HoneyLuka** [comment] 2022-05-04 04:18
iorate may have had some things of its own to deal with recently (I guess) and hasn't committed code in the last month. If anyone has the ability to handle this issue temporarily with a pull request I can release a temporary version for macOS and iOS.

**Comment by Neko288** [comment] 2022-05-04 07:26
私も同じ問題に遭遇しています。
数日前からDuckDuckGoにおいて全くこの拡張機能が機能していません。
ブラックリストには正常に登録されているサイトでも、検索画面に表示されてしまいます。
私の環境 : Windows10, Firefox 100.0(99.0でも同様の問題に遭遇)

I am running into the same problem.
This extension hasn't worked at all in DuckDuckGo for a few days.
Blacklisted sites are also displayed on the search screen.
My environment : Windows10, Firefox 100.0 (Similar problem occurred in 99.0)

**Comment by iorate** [comment] 2022-05-05 10:15
@ everyone
Sorry for my late response.
@kphrx 's solution works well (#228). I'll immediately merge it and release as a patch version.

**Closed** 2022-05-05 10:16 UTC

**Comment by iorate** [comment] 2022-05-05 10:32
Oh, the dialog theme (light/dark) has been reversed for months...

**Comment by Neko288** [comment] 2022-05-05 11:00
I hope you will new release it for Firefox as well!

**Comment by Neko288** [comment] 2022-05-06 12:11
I can now use it completely in Firefox.
Great thanks, iorate.

**Comment by ghjb004** [comment] 2023-05-12 10:37
Please release fix version for Mac App Store as well. Thanks.
