### ISSUE TITLE
Filters aren't working when doing a Google video search

### ISSUE THREAD

**Issue by miso-nikomi-nasu** [iorate/ublacklist#442] opened 2024-04-13 20:55 UTC
## Expected Behavior
completely blocked.

## Actual Behavior
Video sites such as Youtube and TikTok will be displayed without being filtered.

## Steps to Reproduce the Problem

1.Register video sites such as Youtube and TikTok to the filter list.
2.Try searching for videos on Youtube or TikTok with Google video search.

## Specifications

- Browser:Chrome
- Other extensions/add-ons:

- Search engine:Google video search
- Language:Japan
- Region:Japan

**Comment by pubfnbar** [comment] 2024-05-07 17:15
This issue also occurs when doing a regular web search on Startpage.com. Steps to reproduce:
1. Add the blocking rule `*://*.youtube.com/*`
3. Search the following on Startpage.com: "how to clean keyboard"
4. Notice that there are search results from youtube.com

**Comment by aug-dev** [comment] 2024-05-21 02:58
Hey there! @miso-nikomi-nasu 

Are you still facing this issue?

If so, what version of Google are you using? (Mobile or Desktop)

A search query for me to reproduce the issue and a screenshot would *really* help.

**Comment by miso-nikomi-nasu** [comment] 2024-05-24 15:43
I have now searched and investigated.
(Is it because the search engine for Google video search has been updated?)
This problem seems to have been resolved.

**Comment by aug-dev** [comment] 2024-05-25 00:30
I'm also not able to reproduce this issue, so @iorate can probably close it.

Feel free to add new bug reports in the future! :P

**Comment by iorate** [comment] 2024-05-25 09:20
Don't hesitate to request reopening or open a new issue if the problem recurs.

**Closed by iorate** 2024-05-25 09:20 UTC
