### ISSUE TITLE
Stopped working on mobile version of Google Search

### ISSUE THREAD

**Issue by teohhanhui** [iorate/uBlacklist#118] opened 2021-09-14 04:28 UTC
## Expected Behavior
Blacklisted search results are hidden.

## Actual Behavior
uBlacklist doesn't seem to have any effect on the mobile version of Google Search. It works if the desktop site is requested though.

## Steps to Reproduce the Problem

1. Search for anything that's in the blacklist. Make sure you're using the mobile version of Google Search.

## Specifications

- OS: Android 11
- Browser: Firefox Nightly 94.0a1
- Other extensions that might interfere: Google Search Fixer (but it only fakes the UA, so that we get the full modern version that's served to Google Chrome)

**Comment by iorate** [comment] 2021-09-14 09:41
> Other extensions that might interfere: Google Search Fixer (but it only fakes the UA, so that we get the full modern version that's served to Google Chrome)

Currently the modern version of SERP for Google Chrome is not supported, but I'm going to add support for it for iOS support #99 .

**Comment by iorate** [comment] 2021-09-14 09:58
This issue is practically a duplicate of #58 and #85 .
Please follow #99 .

**Closed by iorate** 2021-09-14 09:58 UTC

**Comment by teohhanhui** [comment] 2021-09-14 10:06
Do you mean because it's the "Chrome" version of Google Search? Even though it's not Chrome's extensions API...
