### ISSUE TITLE
Google new layout

### ISSUE THREAD

**Issue by Alex-Mirov** [iorate/ublacklist#470] opened 2024-05-22 17:04 UTC
Hello

Ublacklist won't block any sites on new google layout search at images section when using firefox mobile.

Ublacklist: 8.6.0
Firefox beta: 127.0b3
Phone: Samsung S8 Galaxy
Android: 9 (April 21 Patch)

Thanks

**Comment by aug-dev** [comment] 2024-05-22 23:06
Hi Alex!

Could you please send a screenshot of the problem?

If possible, a search query to reproduce the issue would also be _really_ helpful.

**Comment by Alex-Mirov** [comment] 2024-05-24 04:05
Hello

![Screenshot_20240524-065645_Firefox Beta](https://github.com/iorate/ublacklist/assets/71181695/be59587d-5469-4461-87b8-bb1ccfd66e97)
![Screenshot_20240524-065700_Firefox Beta](https://github.com/iorate/ublacklist/assets/71181695/64fcf80b-9b24-4733-9c83-5b22542041be)
![Screenshot_20240524-065742_Firefox Beta](https://github.com/iorate/ublacklist/assets/71181695/3c86b49c-6cfc-4ed6-bd76-70750669bd91)

I forget to mention also in the video section is not blocking, partial blocking at news section.

Thanks

**Comment by Alex-Mirov** [comment] 2024-05-24 06:51
![Screenshot_20240524-075910_Firefox Beta](https://github.com/iorate/ublacklist/assets/71181695/f3dfde9e-ef62-4edb-baa4-1de7785293ad)

**Comment by aug-dev** [comment] 2024-06-09 00:17
Hey there!

I fixed the issue on Images section and the News section, though the latter will only be available in the next version of uBlacklist.

I'm having trouble to reproduce the issue at the "Videos" section, though.

Are you still having this problem?

If so, please send your version of uBlacklist, and (if possible, of course), send me the region of your Google results, this might help.

**Comment by aug-dev** [comment] 2024-07-20 00:24
@iorate The issue is seemingly fixed and there was no reply after a month.

I think we can close this one.

**Comment by iorate** [comment] 2024-07-21 14:02
@aug-dev I agree with you.

**Closed by iorate** 2024-07-21 14:02 UTC
