### ISSUE TITLE
Can't enable sync with Google Drive in Microsoft Edge

### ISSUE THREAD

**Issue by rahulmangaldas** [iorate/ublacklist#200] opened 2022-02-04 01:11 UTC
## Expected Behavior

Click turn on sync > select Google Drive > Google login > permit uBlacklist

## Actual Behavior

Click turn on sync > select Google Drive > crash

## Steps to Reproduce the Problem

1. Click Turn on sync
1. Select Google Drive

## Specifications

- OS: Windows 10, macOS 15.2
- Browser: Microsoft Edge (works fine in Google Chrome)
- Other extensions that might interfere: don't know

**Comment by iorate** [comment] 2022-02-04 03:08
Probably duplicate of #187 
Try Edge 98, released on Feb 3.
If the problem remains with Edge 98, please leave a comment in #187 .

**Closed by iorate** 2022-02-04 03:08 UTC
