### ISSUE TITLE
Does it still works?

### ISSUE THREAD

**Issue by Nikodemsky** [iorate/uBlacklist#77] opened 2021-02-03 17:32 UTC
## Expected Behavior

Should block all search results with quora.com
(expression is added as `*://www.quora.com/*` )

## Actual Behavior

It shows search results from quora anyway
![purple](https://user-images.githubusercontent.com/14090596/106785485-bc252d00-664d-11eb-95c6-3f24219a43cd.png)

## Specifications

- OS: Win 10
- Browser: Chrome, latest
- Other extensions that might interfere:
Dark Theme for Google (maybe?)

- Active extensions:
Amino: Live CSS Editor
ColorZilla
Dark Theme for Google™
DarkCloud
GhostText
GoFullPage - Full Page Screen Capture
Improve YouTube! (Open-Source for YouTube)
LastPass: Free Password Manager
Toggl Track: Productivity & Time Tracker
uBlacklist
uBlock Origin
Window Resizer
Youtube Uninterrupted

**Comment by iorate** [comment] 2021-02-04 04:36
> Other extensions that might interfere:
Dark Theme for Google (maybe?)

Obviously that is the cause of the problem.
"Dark Theme for Google" replicates `<style id="_goober">...</style>` added by `goober`, which is a CSS-in-JS library used inside uBlacklist, but does not change the `id`. Duplicate ids break `goober` in Chrome.

This problem cannot be fixed on our side.

**Comment by iorate** [comment] 2021-02-07 13:21
I just realized that uBlacklist worked with "Dark Theme for Google" in Firefox.
As it happens, Firefox-specific code to work around a bug of Firefox avoids this problem.
I'm going to port it to Chrome.

**Closed** 2021-02-07 13:23 UTC
