### ISSUE TITLE
block this site link not appearing on search results  - opera - duck duck go

### ISSUE THREAD

**Issue by brenwa** [iorate/ublacklist#506] opened 2024-07-01 15:48 UTC
## Expected Behavior
see the link in order to use the extension

## Actual Behavior
no link

## Steps to Reproduce the Problem

1. use opera (latest version) on linux mint

## Specifications

- Browser: opera
- Other extensions/add-ons: a few including ad blockers all we disabled and browser restarted, still no link 

- Search engine: duck duck go, but doesnt work on google either
- Language: english
- Region: US

**Comment by iorate** [comment] 2024-07-07 12:54
Please check to see if this issue is a duplicate of #288.

**Comment by smadurange** [comment] 2024-07-28 06:54
Not working with Brave either. Not showing the link to block on firefox version 128.0.2 (64-bit).

![image](https://github.com/user-attachments/assets/23022f9c-44eb-4805-ad23-e8d8cf7e6e5c)

**Closed** 2024-08-25 14:52 UTC
