### ISSUE TITLE
Not working. No "block site" button.

### ISSUE THREAD

**Issue by okthanks313** [iorate/ublacklist#304] opened 2022-12-17 03:23 UTC
## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Browser:
- Other extensions/add-ons:

- Search engine:
- Language:
- Region:

**Comment by iorate** [comment] 2022-12-17 04:35
invalid report and probably duplicate of #301

**Closed by iorate** 2022-12-17 04:35 UTC
