### ISSUE TITLE
"Block this site" button in Bing blocks.. Bing.

### ISSUE THREAD

**Issue by Tirith2708** [iorate/ublacklist#271] opened 2022-09-15 17:35 UTC
"Block this site" button blocks "www.bing.com" instead of actual site near the button.

![image](https://user-images.githubusercontent.com/16338228/190472402-c6b8b524-b33a-4c7f-8bb5-53f306515695.png)

**Comment by iorate** [comment] 2022-09-18 11:23
duplicate of #242

**Closed by iorate** 2022-09-18 11:23 UTC
