### ISSUE TITLE
Support a different default search engine, disable access to Google URLs

### ISSUE THREAD

**Issue by jman-schief** [iorate/ublacklist#393] opened 2024-01-01 16:27 UTC
Upon install, this WebExt asks to access by default to a number of [Google URLs](https://github.com/iorate/ublacklist/blob/6d1cc6f640390d8511852a9e043210bf39383198/src/common/search-engines.ts#L26). When adding a second search engine, the browser correctly asks for permission to access the new URLs.

It would nice allowing removing Google from the list of search engines this extension acts upon and remove the corresponding URLs from the allowlist.

The use case being: if I don't use Google at all, this extension does not need to have its URLs in the allowlist.

Thanks!

**Comment by iorate** [comment] 2024-01-08 09:39
duplicate of #52 
My opinion has not changed.

**Closed by iorate** 2024-01-08 09:39 UTC
